version: '3'


volumes:
  reportportal-data:
    # external: true


services:
  sensor0:
    container_name: Sensor0
    build: sensor1

    environment:
      sensorID: 0

    ## Uncomment if needed
    # ports:
    #   - "6969:6969"
    volumes:
      - reportportal-data:/data
    restart: always
  sensor1:
    container_name: Sensor1
    build: sensor1

    environment:
      sensorID: 1

    ## Uncomment if needed
    # ports:
    #   - "6969:6969"
    volumes:
      - reportportal-data:/data
    restart: always
  sensor2:
    container_name: Sensor2
    build: sensor1

    environment:
      sensorID: 2

    ## Uncomment if needed
    # ports:
    #   - "6969:6969"
    volumes:
      - reportportal-data:/data
    restart: always
  sensor3:
    container_name: Sensor3
    build: sensor1

    environment:
      sensorID: 3

    ## Uncomment if needed
    # ports:
    #   - "6969:6969"
    volumes:
      - reportportal-data:/data
    restart: always
  iotgateway:
    container_name: IoT_Gateway

    build: IoTGateway
    ## Uncomment if needed
    # ports:
    #   - "81:81"
    environment:
      numberOfSensors: 4
    volumes:
      - reportportal-data:/data
    restart: always

  server:
    container_name: server

    build: ./Service_Anbieter
    volumes:
      - reportportal-data:/data
    restart: always

  db:
    container_name: db
    build: ./Service_Anbieter
    volumes:
      - reportportal-data:/data
    restart: always
