version: '3'


volumes:
  reportportal-data:
    # external: true

services:
  Sensor1:
    image: ubuntu
    ## Uncomment if needed
    # ports:
    #   - "6969:6969"
    volumes:
      - reportportal-data:/data
    restart: always

  IoTGateway:
    image: ubuntu
    ## Uncomment if needed
    # ports:
    #   - "81:81"
    volumes:
      - reportportal-data:/data
    restart: always