version: '3'


volumes:
  reportportal-data:
    # external: true


services:
  sensor0:
    container_name: Sensor_0
    build: ./src/sensor1

    ## Uncomment if needed
    # ports:
    #   - "6969:6969"
    volumes:
      - reportportal-data:/data
    restart: always
  sensor1:
    container_name: Sensor_1
    build: ./src/sensor1
    ## Uncomment if needed
    # ports:
    #   - "6969:6969"
    volumes:
      - reportportal-data:/data
    restart: always
  sensor2:
    container_name: Sensor_2
    build: ./src/sensor1
    ## Uncomment if needed
    # ports:
    #   - "6969:6969"
    volumes:
      - reportportal-data:/data
    restart: always
  sensor3:
    container_name: Sensor_3
    build: ./src/sensor1
    ## Uncomment if needed
    # ports:
    #   - "6969:6969"
    volumes:
      - reportportal-data:/data
    restart: always
  iotgateway:
    container_name: IoT_Gateway

    build: ./src/IoTGateway
    ## Uncomment if needed
    # ports:
    #   - "81:81"
    environment:
      numberOfSensors: 4
    volumes:
      - reportportal-data:/data
    restart: always
