docker build --tag

docker run -p :/udp mbrel/udp-socket-server:latest

docker run -p :/udp mbrel/udp-socket-server:latest

docker run -p :/udp mbrel/udp-socket-server:latest

docker run -p :/udp mbrel/udp-socket-client:latest
