docker build --tag

docker run -p :/udp mbrel/udp-socket-client:latest
docker run -p :/udp mbrel/udp-socket-client:latest
docker run -p :/udp mbrel/udp-socket-client:latest
docker run -p :/udp mbrel/udp-socket-client:latest

docker run -p 6543:6543/udp mbrel/udp-socket-server:latest
